version: "3"

networks:
  vermillion-net:
    driver: bridge

volumes:
  broker-data:
  es-data:
  redis-data:

services:

  vertx:
    image: iudx/java
    container_name: vertx
    hostname: vertx
    restart: on-failure
    ports:
      - "${HTTPS_PORT}:443"
    networks:
      - vermillion-net
    volumes:
      - ../api-server:/api-server/
    env_file:
      - vermillion.conf
    environment:
      - WAIT_HOSTS=rabbit:5672,authenticator:80,redis:6379
      - WAIT_HOSTS_TIMEOUT=120
      - PROJECT_DIR=api-server
      - JAR_NAME=api-server-fat.jar

  authenticator:
    image: iudx/java
    container_name: authenticator
    hostname: authenticator
    restart: on-failure
    networks:
      - vermillion-net
    volumes:
      - ../authenticator:/authenticator/
    env_file:
      - vermillion.conf
    environment:
      - WAIT_HOSTS=redis:6379
      - PROJECT_DIR=authenticator
      - JAR_NAME=authenticator-fat.jar

  rabbit:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: ${RABBITMQ_HOSTNAME}
    restart: on-failure
    hostname: rabbit
    ports:
      - "${RABBITMQ_SSL_PORT}:5671"
      - "${RABBITMQ_TCP_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - vermillion-net
    volumes:
      - broker-data:/var/lib/rabbitmq/
      - ../conf/rabbitmq/:/etc/rabbitmq/:rw
    env_file:
      - vermillion.conf
  
  elasticsearch:
    image: elasticsearch:${ES_VERSION}
    container_name: elasticsearch
    hostname: ${ES_HOSTNAME}
    ports:
      - "${ES_PORT}:9200"
    restart: on-failure
    networks:
      - vermillion-net
    volumes:
      - es-data:/usr/share/elasticsearch/data
    env_file:
      - vermillion.conf
    environment:
      - discovery.type=single-node

  dbconnector:
    image: iudx/db-connector
    container_name: connector
    hostname: connector
    restart: on-failure
    networks:
      - vermillion-net
    volumes:
      - ../db-connector:/db-connector/
    env_file:
      - vermillion.conf
    environment:
      - WAIT_HOSTS=rabbit:5672,authenticator:80,elasticsearch:9200
      - WAIT_HOSTS_TIMEOUT=600

  redis:
    image: bitnami/redis
    container_name: redis
    hostname: ${REDIS_HOSTNAME}
    restart: on-failure
    networks:
      - vermillion-net
    volumes:
      - redis-data:/bitnami/redis/data
    ports:
      - "${REDIS_TCP_PORT}:6379"
    env_file:
      - vermillion.conf
    environment:
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
